var lzma_decompress=function(){var c={A:function(){this.C=0}};c.A.prototype.create=function(a){this.F&&this.C===a||(this.F=new Uint8Array(a));this.C=a;this.ba=this.s=0};c.A.prototype.flush=function(){var a=this.s-this.ba;if(0!==a){if(this.u.qa)this.u.qa(this.F,a);else for(var b=0;b<a;b++)this.u.Na(this.F[b]);this.s>=this.C&&(this.s=0);this.ba=this.s}};c.A.prototype.R=function(){this.flush();this.u=null};c.A.prototype.ca=function(a){this.R();this.u=a};c.A.prototype.g=function(a){a||(this.s=this.ba=0)};c.A.prototype.ua=
function(a,b){var d=this.s-a-1;for(0>d&&(d+=this.C);b--;)d>=this.C&&(d=0),this.F[this.s++]=this.F[d++],this.s>=this.C&&this.flush()};c.A.prototype.Ga=function(a){this.F[this.s++]=a;this.s>=this.C&&this.flush()};c.A.prototype.na=function(a){a=this.s-a-1;0>a&&(a+=this.C);return this.F[a]};c.G=function(){};c.G.prototype.ca=function(a){this.u=a};c.G.prototype.R=function(){this.u=null};c.G.prototype.g=function(){var a=5;this.l=0;for(this.h=-1;a--;)this.l=this.l<<8|this.u.j()};c.G.prototype.wa=function(a){for(var b=
0,d;a--;)this.h>>>=1,d=this.l-this.h>>>31,this.l-=this.h&d-1,b=b<<1|1-d,0===(this.h&4278190080)&&(this.l=this.l<<8|this.u.j(),this.h<<=8);return b};c.G.prototype.m=function(a,b){var d=a[b],e=(this.h>>>11)*d;if((this.l^2147483648)<(e^2147483648))return this.h=e,a[b]+=2048-d>>>5,0===(this.h&4278190080)&&(this.l=this.l<<8|this.u.j(),this.h<<=8),0;this.h-=e;this.l-=e;a[b]-=d>>>5;0===(this.h&4278190080)&&(this.l=this.l<<8|this.u.j(),this.h<<=8);return 1};c.v=function(a,b){for(;b--;)a[b]=1024};c.o=function(a){this.Z=
[];this.P=a};c.o.prototype.g=function(){c.v(this.Z,1<<this.P)};c.o.prototype.decode=function(a){for(var b=1,d=this.P;d--;)b=b<<1|a.m(this.Z,b);return b-(1<<this.P)};c.o.prototype.Ha=function(a){for(var b=1,d=0,e=0,f;e<this.P;++e)f=a.m(this.Z,b),b=b<<1|f,d|=f<<e;return d};c.Ia=function(a,b,d,e){for(var f=1,h=0,k=0,l;k<e;++k)l=d.m(a,b+f),f=f<<1|l,h|=l<<k;return h};c.I=function(){this.S=[];this.X=[];this.Y=[];this.da=new c.o(8);this.J=0};c.I.prototype.create=function(a){for(;this.J<a;++this.J)this.X[this.J]=
new c.o(3),this.Y[this.J]=new c.o(3)};c.I.prototype.g=function(){var a=this.J;for(c.v(this.S,2);a--;)this.X[a].g(),this.Y[a].g();this.da.g()};c.I.prototype.decode=function(a,b){return 0===a.m(this.S,0)?this.X[b].decode(a):0===a.m(this.S,1)?8+this.Y[b].decode(a):16+this.da.decode(a)};c.L=function(){this.O=[]};c.L.prototype.g=function(){c.v(this.O,768)};c.L.prototype.ya=function(a){var b=1;do b=b<<1|a.m(this.O,b);while(256>b);return b&255};c.L.prototype.za=function(a,b){var d=1;do{var e=b>>7&1;b<<=
1;var f=a.m(this.O,(1+e<<8)+d);d=d<<1|f;if(e!==f){for(;256>d;)d=d<<1|a.m(this.O,d);break}}while(256>d);return d&255};c.M=function(){};c.M.prototype.create=function(a,b){var d;if(!this.N||this.K!==b||this.$!==a)for(this.$=a,this.ra=(1<<a)-1,this.K=b,this.N=[],d=1<<this.K+this.$;d--;)this.N[d]=new c.L};c.M.prototype.g=function(){for(var a=1<<this.K+this.$;a--;)this.N[a].g()};c.M.prototype.Ca=function(a,b){return this.N[((a&this.ra)<<this.K)+((b&255)>>>8-this.K)]};c.D=function(){this.B=new c.A;this.i=
new c.G;this.ea=[];this.ga=[];this.ha=[];this.ia=[];this.ja=[];this.fa=[];this.H=[];this.la=[];this.ka=new c.o(4);this.V=new c.I;this.aa=new c.I;this.W=new c.M;this.U=this.T=-1;this.H[0]=new c.o(6);this.H[1]=new c.o(6);this.H[2]=new c.o(6);this.H[3]=new c.o(6)};c.D.prototype.Ja=function(a){if(0>a)return!1;this.T!==a&&(this.T=a,this.U=Math.max(this.T,1),this.B.create(Math.max(this.U,4096)));return!0};c.D.prototype.Ka=function(a,b,d){var e=1<<d;if(8<a||4<b||4<d)return!1;this.W.create(b,a);this.V.create(e);
this.aa.create(e);this.sa=e-1;return!0};c.D.prototype.La=function(a){if(!this.Ka(a.Da,a.Ea,a.Fa))throw Error;if(!this.Ja(a.Ba))throw Error;};c.D.prototype.xa=function(a){if(13>a.size)return!1;var b=a.j();var d=b%9;b=~~(b/9);var e=b%5;b=~~(b/5);var f=a.j();f|=a.j()<<8;f|=a.j()<<16;f+=16777216*a.j();var h=a.j();h|=a.j()<<8;h|=a.j()<<16;h+=16777216*a.j();a.j();a.j();a.j();a.j();return{Da:d,Ea:e,Fa:b,Ba:f,Ma:h}};c.D.prototype.g=function(){var a=4;this.B.g(!1);c.v(this.ea,192);c.v(this.fa,192);c.v(this.ga,
12);c.v(this.ha,12);c.v(this.ia,12);c.v(this.ja,12);c.v(this.la,114);for(this.W.g();a--;)this.H[a].g();this.V.g();this.aa.g();this.ka.g();this.i.g()};c.D.prototype.va=function(a,b,d){var e=0,f=0,h=0,k=0,l=0,m=0,g=0;this.i.ca(a);this.B.ca(b);for(this.g();0>d||m<d;)if(a=m&this.sa,0===this.i.m(this.ea,(e<<4)+a))g=this.W.Ca(m++,g),g=7<=e?g.za(this.i,this.B.na(f)):g.ya(this.i),this.B.Ga(g),e=4>e?0:e-(10>e?3:6);else{if(1===this.i.m(this.ga,e))g=0,0===this.i.m(this.ha,e)?0===this.i.m(this.fa,(e<<4)+a)&&
(e=7>e?9:11,g=1):(0===this.i.m(this.ia,e)?b=h:(0===this.i.m(this.ja,e)?b=k:(b=l,l=k),k=h),h=f,f=b),0===g&&(g=2+this.aa.decode(this.i,a),e=7>e?8:11);else if(l=k,k=h,h=f,g=2+this.V.decode(this.i,a),e=7>e?7:10,a=this.H[5>=g?g-2:3].decode(this.i),4<=a)if(b=(a>>1)-1,f=(2|a&1)<<b,14>a)f+=c.Ia(this.la,f-a-1,this.i,b);else{if(f+=this.i.wa(b-4)<<4,f+=this.ka.Ha(this.i),0>f){if(-1===f)break;return!1}}else f=a;if(f>=m||f>=this.U)return!1;this.B.ua(f,g);m+=g;g=this.B.na(0)}this.B.flush();this.B.R();this.i.R();
return!0};c.oa=function(a){this.ta=new Uint8Array(a);this.size=a.byteLength;this.offset=0};c.oa.prototype.j=function(){return this.ta[this.offset++]};c.pa=function(){this.size=0;this.ma=[]};c.pa.prototype.qa=function(a,b){this.ma.push(new Uint8Array(a.subarray(0,b)));this.size+=b};c.Aa=function(a){var b=new c.oa(a);a=new c.pa;var d=new c.D,e=d.xa(b),f=e.Ma;d.La(e);if(!d.va(b,a,f))throw Error;b=a.ma;a=new Uint8Array(a.size);for(e=d=0;d<b.length;d++)a.set(b[d],e),e+=b[d].length;b.length=0;return a};
return c.Aa}();